# Generated by Django 4.1.1 on 2022-09-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(blank=True, default='ShxlKvXz', max_length=8, null=True, unique=True),
        ),
    ]
