# Generated by Django 4.1.1 on 2022-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_exam_date_exam_date_alter_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('STARTED', 'STARTED'), ('SUBMITTED', 'SUBMITTED')], default='NOT_STARTED', max_length=100),
        ),
    ]
