# Generated by Django 4.1.1 on 2022-09-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_answersheet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='description',
            new_name='instruction',
        ),
        migrations.AlterField(
            model_name='question',
            name='mark',
            field=models.IntegerField(default=1),
        ),
    ]
