# Generated by Django 4.1.1 on 2022-09-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_rename_description_exam_instruction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='code',
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(default=None),
        ),
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(default=None),
        ),
    ]
