# Generated by Django 4.1.1 on 2022-09-30 14:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_exam_code_alter_exam_date_alter_exam_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SingleMCQ', 'SingleMCQ'), ('MultipleMCQ', 'MultipleMCQ'), ('TrueFalse', 'TrueFalse'), ('ESSAY', 'ESSAY')], max_length=100),
        ),
    ]
