# Generated by Django 4.1.1 on 2022-09-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_option_mark_alter_exam_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='mark',
        ),
    ]
