# Generated by Django 4.1.1 on 2022-09-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_option_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exam.exam'),
        ),
    ]
