# Generated by Django 4.1.1 on 2022-09-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_option_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exam.answer'),
        ),
    ]
