# Generated by Django 4.1.1 on 2022-09-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_option_exam_remove_option_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='questions', to='exam.option'),
        ),
    ]
