# Generated by Django 4.1.1 on 2022-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='mark',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SingleMCQ', 'SingleMCQ'), ('MultipleMCQ', 'MultipleMCQ'), ('TrueFalse', 'TrueFalse'), ('Subjective', 'Subjective')], max_length=100),
        ),
    ]
