# Generated by Django 4.1.1 on 2022-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_answer_answered_alter_answersheet_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='total_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
