# Generated by Django 4.1.1 on 2022-10-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_answersheet_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
