# Generated by Django 4.1.1 on 2022-10-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
    ]
